title: Your Site Title
email: youremail@example.com
description: "A description of your site"
baseurl: "" # Base URL for the site (e.g., /blog)
url: "http://yourdomain.com" # URL of your site
theme: minima # Default theme is "minima"
