# title: Your Site Title
# email: youremail@example.com
# description: "A description of your site"
# baseurl: "" # Base URL for the site (e.g., /blog)
# url: "http://yourdomain.com" # URL of your site
# theme: minima # Default theme is "minima"

# # Markdown Processor Settings
# kramdown:
#   input: GFM  # GitHub Flavored Markdown (optional)
#   hard_wrap: false  # Enables/disables <br> on single line breaks
#   auto_ids: true    # Automatically generates IDs for headers
#   syntax_highlighter: rouge  # Adds syntax highlighting for code blocks

# # Build Settings
# theme: minima  # Optional, set a theme
# plugins:       # Optional, include any Jekyll plugins here
#   - jekyll-feed  # Example: A plugin for RSS feeds

# # Permalinks
# permalink: pretty  # Clean URLs without .html extension